In [365]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# FASE 1 (PARTE I)

- ARCHIVO CUSTOMER LOYALTY HISTORY

In [366]:
# Lectura del archivo Loyalty 
df_loyalty = pd.read_csv("Customer Loyalty History.csv") 
df_loyalty.head()

#unir año y mes

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

In [367]:
#Verificación de dimensiones
df_loyalty.shape

(16737, 16)

In [368]:
# verificar detalle de las columnas (años y meses cambiar formato)
df_loyalty.info()

<class 'pandas.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  str
 2   Province            16737 non-null  str
 3   City                16737 non-null  str
 4   Postal Code         16737 non-null  str
 5   Gender              16737 non-null  str
 6   Education           16737 non-null  str
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  str
 9   Loyalty Card        16737 non-null  str
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  str
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), str(9)
memory usage: 2.0 MB

In [369]:
# Detectar columnas con nulos (3) 
round(df_loyalty.isna().sum()/df_loyalty.shape[0]*100),2 #redondeo a 2 decimales

(Loyalty Number         0.0
 Country                0.0
 Province               0.0
 City                   0.0
 Postal Code            0.0
 Gender                 0.0
 Education              0.0
 Salary                25.0
 Marital Status         0.0
 Loyalty Card           0.0
 CLV                    0.0
 Enrollment Type        0.0
 Enrollment Year        0.0
 Enrollment Month       0.0
 Cancellation Year     88.0
 Cancellation Month    88.0
 dtype: float64,
 2)

In [ ]:
#verifico duplicados
df_loyalty.duplicated().sum()

np.int64(0)

In [372]:
#Datos estadisticos (columna Salario -)
df_loyalty.describe(include=np.number).T

,count,mean,std,min,25%,50%,75%,max
Loyalty Number,16737.0,549735.880445,258912.132453,100018.00,326603.00,550434.00,772019.00,999986.00
Salary,12499.0,79245.609409,35008.297285,-58486.00,59246.50,73455.00,88517.50,407228.00
CLV,16737.0,7988.896536,6860.982280,1898.01,3980.84,5780.18,8940.58,83325.38
Enrollment Year,16737.0,2015.253211,1.979111,2012.00,2014.00,2015.00,2017.00,2018.00
Enrollment Month,16737.0,6.669116,3.398958,1.00,4.00,7.00,10.00,12.00
Cancellation Year,2067.0,2016.503145,1.380743,2013.00,2016.00,2017.00,2018.00,2018.00
Cancellation Month,2067.0,6.962748,3.455297,1.00,4.00,7.00,10.00,12.00

In [ ]:
#clientes con salarios en negativo y busco relación ( promotion: 2018, año de suscripción: 2018, Meses 2-3-4)
df_loyalty[df_loyalty["Salary"] < 0]

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
1082,542976,Canada,Quebec,Montreal,H2Y 4R4,Male,High School or Below,-49830.0,Divorced,Star,24127.50,2018 Promotion,2018,3,NaN,NaN
1894,959977,Canada,British Columbia,Vancouver,V5R 1W3,Female,Bachelor,-12497.0,Married,Aurora,9453.00,2018 Promotion,2018,3,NaN,NaN
2471,232755,Canada,British Columbia,Vancouver,V1E 4R6,Female,Bachelor,-46683.0,Single,Nova,4787.81,2018 Promotion,2018,3,NaN,NaN
3575,525245,Canada,British Columbia,Victoria,V10 6T5,Male,Bachelor,-45962.0,Married,Star,2402.33,2018 Promotion,2018,3,NaN,NaN
3932,603070,Canada,British Columbia,West Vancouver,V6V 8Z3,Female,Bachelor,-19325.0,Single,Star,2893.74,2018 Promotion,2018,3,NaN,NaN
4712,491242,Canada,British Columbia,Dawson Creek,U5I 4F1,Male,Bachelor,-43234.0,Married,Star,7597.91,2018 Promotion,2018,3,NaN,NaN
6560,115505,Canada,Newfoundland,St. John's,A1C 6H9,Male,Bachelor,-10605.0,Married,Nova,5860.17,2018 Promotion,2018,4,NaN,NaN
6570,430398,Canada,Newfoundland,St. John's,A1C 6H9,Male,Bachelor,-17534.0,Married,Nova,49423.80,2018 Promotion,2018,3,NaN,NaN
7373,152016,Canada,Ontario,Toronto,P1J 8T7,Female,Bachelor,-58486.0,Married,Aurora,5067.21,2018 Promotion,2018,2,NaN,NaN
8576,194065,Canada,Ontario,Sudbury,M5V 1G5,Female,Bachelor,-31911.0,Married,Nova,2888.85,2018 Promotion,2018,2,NaN,NaN
8767,212128,Canada,Ontario,Toronto,P2T 6G3,Male,Bachelor,-49001.0,Married,Nova,3130.68,2018 Promotion,2018,2,NaN,NaN
10232,790475,Canada,Ontario,Trenton,K8V 4B2,Female,Bachelor,-34079.0,Married,Nova,12913.50,2018 Promotion,2018,2,NaN,NaN
11635,366599,Canada,Ontario,Toronto,M1R 4K3,Female,Bachelor,-9081.0,Married,Star,6915.73,2018 Promotion,2018,4,NaN,NaN
12596,436087,Canada,Quebec,Montreal,H2T 9K8,Male,Bachelor,-46470.0,Married,Star,4786.89,2018 Promotion,2018,4,2018.0,8.0
13564,364596,Canada,Quebec,Tremblant,H5Y 2S9,Female,Bachelor,-26322.0,Single,Aurora,16710.84,2018 Promotion,2018,4,2018.0,12.0
14327,239955,Canada,Quebec,Hull,J8Y 3Z5,Female,Bachelor,-47310.0,Married,Nova,6366.23,2018 Promotion,2018,3,NaN,NaN
14355,347013,Canada,Quebec,Quebec City,G1B 3L5,Male,Bachelor,-39503.0,Married,Nova,6446.71,2018 Promotion,2018,3,NaN,NaN
15416,729561,Canada,Quebec,Quebec City,G1B 3L5,Female,Bachelor,-19332.0,Divorced,Star,5308.29,2018 Promotion,2018,2,NaN,NaN
16431,734647,Canada,Saskatchewan,Regina,S1J 3C5,Male,Bachelor,-46303.0,Married,Nova,11280.73,2018 Promotion,2018,4,NaN,NaN
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN

In [374]:
clientes_salario_negativo=df_loyalty[df_loyalty["Salary"] < 0]
#confirmo la cantidad
print(clientes_salario_negativo.shape)

(20, 16)

In [ ]:
# Todos los registros son del pais Canadá
df_loyalty.describe(include="str").T

                 count unique       top   freq
Country          16737      1    Canada  16737
Province         16737     11   Ontario   5404
City             16737     29   Toronto   3351
Postal Code      16737     55   V6E 3D9    911
Gender           16737      2    Female   8410
Education        16737      5  Bachelor  10475
Marital Status   16737      3   Married   9735
Loyalty Card     16737      3      Star   7637
Enrollment Type  16737      2  Standard  15766

In [376]:
#Analizo si hay datos duplicados (error de escritura)
columnas_revisar = ["Country", "Province", "Gender", "Education", "Marital Status", "Loyalty Card", "Enrollment Type"]

for col in columnas_revisar:
    print(f"Columna: {col}")
    print(df_loyalty[col].unique())
    print("-" * 50)

Columna: Country
<StringArray>
['Canada']
Length: 1, dtype: str
--------------------------------------------------
Columna: Province
<StringArray>
[             'Ontario',              'Alberta',     'British Columbia',
               'Quebec',                'Yukon',        'New Brunswick',
             'Manitoba',          'Nova Scotia',         'Saskatchewan',
         'Newfoundland', 'Prince Edward Island']
Length: 11, dtype: str
--------------------------------------------------
Columna: Gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
--------------------------------------------------
Columna: Education
<StringArray>
['Bachelor', 'College', 'Master', 'High School or Below', 'Doctor']
Length: 5, dtype: str
--------------------------------------------------
Columna: Marital Status
<StringArray>
['Married', 'Divorced', 'Single']
Length: 3, dtype: str
--------------------------------------------------
Columna: Loyalty Card
<StringArray>
['Star', 'Aurora', 'Nova']
Length: 3, dtype: str
--------------------------------------------------
Columna: Enrollment Type
<StringArray>
['Standard', '2018 Promotion']
Length: 2, dtype: str
--------------------------------------------------

In [377]:
#Analizo los datos en columnas numericas (error de escritura) todos ok, hay numos pero son losdel 88%
columnas_num = ["Enrollment Year", "Enrollment Month", "Cancellation Year", "Cancellation Month"]

for col in columnas_num:
    print(f"Columna: {col}")
    print(df_loyalty[col].unique())
    print("-" * 50)

Columna: Enrollment Year
[2016 2014 2013 2012 2015 2018 2017]
--------------------------------------------------
Columna: Enrollment Month
[ 2  3  7 10  5  6 12  1 11  8  4  9]
--------------------------------------------------
Columna: Cancellation Year
[  nan 2018. 2015. 2017. 2014. 2016. 2013.]
--------------------------------------------------
Columna: Cancellation Month
[nan  1. 12.  4.  2.  7. 11.  5.  6. 10.  8.  9.  3.]
--------------------------------------------------

- Archivo FLIGHT ACTIVITY

In [378]:
# Lectura del csv flight Activity
df_flight=pd.read_csv("Customer Flight Activity.csv")
df_flight.head()

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0
3,100214,2017,1,0,0,0,0,0.0,0,0
4,100272,2017,1,0,0,0,0,0.0,0,0

In [ ]:
#verifico dimensiones del dataset
df_flight.shape

(405624, 10)

In [ ]:
#reviso tipo y formato
df_flight.info()

<class 'pandas.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               405624 non-null  int64
 1   Year                         405624 non-null  int64
 2   Month                        405624 non-null  int64
 3   Flights Booked               405624 non-null  int64
 4   Flights with Companions      405624 non-null  int64
 5   Total Flights                405624 non-null  int64
 6   Distance                     405624 non-null  int64
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64
 9   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.9 MB

In [381]:
#verifico duplicados 
df_flight.duplicated().sum()

np.int64(1864)

In [382]:
#Aislo los duplicados y sus copias
vuelos_duplicados = df_flight[df_flight.duplicated(keep=False)]
vuelos_duplicados

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
41,101902,2017,1,0,0,0,0,0.0,0,0
42,101902,2017,1,0,0,0,0,0.0,0,0
226,112142,2017,1,0,0,0,0,0.0,0,0
227,112142,2017,1,0,0,0,0,0.0,0,0
477,126100,2017,1,0,0,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...
405111,971370,2018,12,0,0,0,0,0.0,0,0
405409,988392,2018,12,0,0,0,0,0.0,0,0
405410,988392,2018,12,0,0,0,0,0.0,0,0
405436,989528,2018,12,0,0,0,0,0.0,0,0
405437,989528,2018,12,0,0,0,0,0.0,0,0

In [383]:
#Elimino duplicados 
df_flight.drop_duplicates(inplace = True)

In [394]:
#compruebo que ya no hay
df_flight.duplicated().sum()

np.int64(0)

In [385]:
#Detectar nulos (0 columnas con nulos)
round(df_flight.isna().sum()/df_flight.shape[0]*100),2

(Loyalty Number                 0.0
 Year                           0.0
 Month                          0.0
 Flights Booked                 0.0
 Flights with Companions        0.0
 Total Flights                  0.0
 Distance                       0.0
 Points Accumulated             0.0
 Points Redeemed                0.0
 Dollar Cost Points Redeemed    0.0
 dtype: float64,
 2)

In [ ]:
#Estadisticas del dataset
df_flight.describe(include=np.number).T #2017 al 2018 / maximo e viajes en un cliente 32

,count,mean,std,min,25%,50%,75%,max
Loyalty Number,403760.0,549875.383713,258961.514684,100018.0,326699.0,550598.0,772152.0,999986.0
Year,403760.0,2017.500352,0.500000,2017.0,2017.0,2018.0,2018.0,2018.0
Month,403760.0,6.501335,3.451982,1.0,4.0,7.0,10.0,12.0
Flights Booked,403760.0,4.134050,5.230064,0.0,0.0,1.0,8.0,21.0
Flights with Companions,403760.0,1.036569,2.080472,0.0,0.0,0.0,1.0,11.0
Total Flights,403760.0,5.170619,6.526858,0.0,0.0,1.0,10.0,32.0
Distance,403760.0,1214.460979,1434.098521,0.0,0.0,525.0,2342.0,6293.0
Points Accumulated,403760.0,124.263761,146.696179,0.0,0.0,53.0,240.0,676.5
Points Redeemed,403760.0,30.838587,125.758002,0.0,0.0,0.0,0.0,876.0
Dollar Cost Points Redeemed,403760.0,2.495973,10.172033,0.0,0.0,0.0,0.0,71.0

In [ ]:
#quienes son los viajeros mas frecuentes (27) / mes alta demanda julio
viajeros_frecuentes = df_flight[df_flight['Total Flights'] == 32]
viajeros_frecuentes

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
102525,160773,2017,7,21,11,32,5888,588.0,0,0
107260,413741,2017,7,21,11,32,2368,236.0,0,0
109113,510513,2017,7,21,11,32,5984,598.0,0,0
110368,577156,2017,7,21,11,32,5536,553.0,0,0
111951,661502,2017,7,21,11,32,2848,284.0,0,0
196563,708807,2018,7,21,11,32,4896,489.0,748,60
305777,184151,2018,7,21,11,32,3776,377.0,0,0
306166,204000,2018,7,21,11,32,2720,272.0,0,0
308138,310700,2018,7,21,11,32,4960,496.0,0,0
308475,328303,2018,7,21,11,32,5152,515.0,0,0
309616,389551,2018,7,21,11,32,2368,236.0,0,0
309880,403893,2018,7,21,11,32,4928,492.0,0,0
310020,411523,2018,7,21,11,32,5344,534.0,0,0
311848,506170,2018,7,21,11,32,4768,476.0,0,0
312167,523642,2018,7,21,11,32,5888,588.0,0,0
312592,546997,2018,7,21,11,32,4192,419.0,0,0
314716,659205,2018,7,21,11,32,2720,272.0,0,0
315068,677527,2018,7,21,11,32,2496,249.0,0,0
315511,700918,2018,7,21,11,32,3648,364.0,0,0
316065,729561,2018,7,21,11,32,5536,553.0,0,0
317920,828895,2018,7,21,11,32,3808,380.0,0,0
317996,832864,2018,7,21,11,32,3616,361.0,0,0
318331,849425,2018,7,21,11,32,2752,275.0,0,0
320623,972298,2018,7,21,11,32,3040,304.0,0,0
320974,459164,2018,7,21,11,32,2784,278.0,513,42
380028,713085,2018,7,21,11,32,2208,220.0,492,40
396749,286551,2018,7,21,11,32,2144,214.0,831,67

# FASE 1 (PARTE II)

- Transformación de datos

In [391]:
#Unificamos los archivos
df_unificado = pd.merge(df_flight, df_loyalty, on='Loyalty Number', how='left')

In [ ]:
#verifico nuevas dimensiones
df_unificado.shape

(403760, 25)